### ISSUE TITLE
Build with default config fails for MaOS 10.14.4 (18E226)

### ISSUE THREAD

**Issue by marekkowalczyk** [LukeSmithxyz/st#60]
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [st] Error 1
```

Abandon all hope those who have joined the Mac cult?

**Comment by LukeSmithxyz** [comment]
This is not software for Mac OS.
